### ISSUE TITLE
Moveit2 demo for Nuttx+New board

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro-ROS_moveit2_demo#2]
Dear @pablogs9 

I would like to know about moveit2_demo. Is it possible to make this demo using with nuttx +stm32f429disco or waveshare board? Can you guide me alittle more about this demo.

Best Reards,
Marlar

**Comment by pablogs9** [comment]
Hello @MARLARCHAN, you can find a detailed description in [this video](https://www.youtube.com/watch?v=wgIKGUGSX7Y). Feel free to ask any other doubt.

We don't officially support Nuttx + stm32f429disco + micro-ROS, nor any board from waveshare, so I guess that the easiest way to reproduce this demo is with the hardware and RTOS described in this repo.
