### ISSUE TITLE
Gives an error (tf2_msgs/msg/tf_message.h: No such file or directory)

### ISSUE THREAD

**Issue by Altaibaatar** [micro-ROS/micro-ROS_moveit2_demo#3]
Hello, I tried to reproduce the demo (micro-ROS meets MoveIt). But when I try to build the firmware with the command
[ros2 run micro_ros_setup build_firmware.sh], this give following error.

`[ 12%] Building C object CMakeFiles/app.dir/src/main.c.obj
/microros_ws/firmware/zephyr_apps/apps/attitude_estimator/src/main.c:24:10: fatal error: tf2_msgs/msg/tf_message.h: No such file or directory
   24 | #include <tf2_msgs/msg/tf_message.h>`

**Comment by pablogs9** [comment]
Hello, sorry for this. If you visit the page of the Zephyr app you can see the instructions to install this: https://github.com/micro-ROS/zephyr_apps/tree/foxy/apps/attitude_estimator

I'm going to update this readme also. Sorry for the inconvenience.

**Comment by Altaibaatar** [comment]
Thank you, pablogs9! Your instruction solved the issue.
