### ISSUE TITLE
Config Firmware issue for Movelt  using Zephyr

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro-ROS_moveit2_demo#6]
Hi @pablogs9 
    I'm trying to test Movelt using Zephyr. After I create firmware, I cannot config firmware and the error is the following:

$ ros2 run micro_ros_setup configure_firmware.sh attitude_estimator -t serial -d 1
Configuring firmware for zephyr platform discovery_l475_iot1
Using serial device.
Please check firmware/zephyr_apps/microros_extensions/microros_transports.h
for configuring serial device before build.

I've no idea what I need to update into microros_transport.h.Can you help me for this issue?

**Comment by pablogs9** [comment]
There is no problem, it tells that you should check [this file](https://github.com/micro-ROS/zephyr_apps/blob/89e85c8cf29647d276203735a49a41ecbc4b8dd1/microros_extensions/microros_transports.h#L47) to configure the serial port that micro-ROS will use.
