### ISSUE TITLE
Moveit Attitude_estimator Example Firmware build error

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro-ROS_moveit2_demo#7]
Dear @pablogs9 
   I'm trying to build moveit attitude_estimator example.
I already put geometry2/tf2_msgs. After that when I build firmware, I found out the issue like this.

--- stderr: tf2                                             
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "Findconsole_bridge_vendor.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "console_bridge_vendor", but CMake did not find one.

  Could not find a package configuration file provided by
  "console_bridge_vendor" with any of the following names:

    console_bridge_vendorConfig.cmake
    console_bridge_vendor-config.cmake

  Add the installation prefix of "console_bridge_vendor" to CMAKE_PREFIX_PATH
  or set "console_bridge_vendor_DIR" to a directory containing one of the
  above files.  If "console_bridge_vendor" provides a separate development
  package or SDK, be sure it has been installed.
---
Failed   <<< tf2 [0.78s, exited with code 1]
Aborted  <<< tf2_msgs [1.16s]                                         
Aborted  <<< test_rmw_implementation [2.00s]
Aborted  <<< diagnostic_msgs [1.21s]                                  
Aborted  <<< nav_msgs [1.23s]
Aborted  <<< trajectory_msgs [1.23s]                                  
Aborted  <<< shape_msgs [1.24s]
Aborted  <<< sensor_msgs [1.33s]
Aborted  <<< visualization_msgs [1.28s]
Aborted  <<< rcl [2.25s]                              

Summary: 45 packages finished [28.6s]
  1 package failed: tf2
  9 packages aborted: diagnostic_msgs nav_msgs rcl sensor_msgs shape_msgs test_rmw_implementation tf2_msgs trajectory_msgs visualization_msgs
  51 packages had stderr output: action_msgs actionlib_msgs builtin_interfaces composition_interfaces diagnostic_msgs example_interfaces geometry_msgs libyaml_vendor lifecycle_msgs micro_ros_msgs microcdr microxrcedds_client nav_msgs rcl rcl_interfaces rcl_logging_noop rcutils rmw rmw_implementation rmw_implementation_cmake rmw_microxrcedds rosgraph_msgs rosidl_adapter rosidl_cmake rosidl_default_generators rosidl_default_runtime rosidl_generator_c rosidl_generator_dds_idl rosidl_parser rosidl_runtime_c rosidl_typesupport_c rosidl_typesupport_interface rosidl_typesupport_microxrcedds_c rosidl_typesupport_microxrcedds_c_tests rosidl_typesupport_microxrcedds_test_msg sensor_msgs shape_msgs statistics_msgs std_msgs std_srvs test_interface_files test_msgs test_rmw_implementation tf2 tf2_msgs tinydir_vendor tracetools tracetools_test trajectory_msgs unique_identifier_msgs visualization_msgs
  18 packages not processed
make[3]: *** [Makefile:57: colcon_compile] Error 1
make[2]: *** [CMakeFiles/microroslib_project.dir/build.make:86: microros_extensions/src/microroslib_project-stamp/microroslib_project-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:2008: CMakeFiles/microroslib_project.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
FATAL ERROR: command exited with status 2: /usr/bin/cmake --build /home/marlar/movelt/firmware/build

Please advise me.

**Comment by MARLARCHAN** [comment]
Hi @pablogs9 
    Sorry for my duplicate issue. Please guide me for this issue.

**Comment by MARLARCHAN** [comment]
Hi @pablogs9 
       Now I got to build it. Thanks.

**Comment by pablogs9** [comment]
Please at least explain what you did wrong in order to have the answer for other users.

**Comment by MARLARCHAN** [comment]
Hi @pablogs9 
   $rm -rf geometry2
   After adding tf2_msgs from geometry2 folder, make sure clean or remove the previous firmware build folder. If not, it will conflict with the current updated one. After remove previous build folder, firmware can build again.
