### ISSUE TITLE
Error when movelt demo simulation installation

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro-ROS_moveit2_demo#8]
Dear @pablogs9 
   Where can I clone movelt demo simulation installation? 

```
git clone https://github.com/micro-ROS/micro-ROS_moveit2_demo
colcon build --event-handlers desktop_notification- status- --packages-select microros_moveit2_demo --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
source install/local_setup.bash
```

I tried install in the same project, but I found issue when I launch .py
ros2 launch microros_moveit2_demo microros_moveit2_demo.launch.py

Error:
```
ros2 launch microros_moveit2_demo microros_moveit2_demo.launch.pyPackage 'microros_moveit2_demo' not found: "package 'microros_moveit2_demo' not found, searching: ['zephyr_movelt/install/rosidl_typesupport_microxrcedds_c', 'zephyr_movelt/install/micro_ros_agent', 'zephyr_movelt/install/micro_ros_setup', 'zephyr_movelt/install/micro_ros_msgs', '/opt/ros/foxy']"
```

Please give me any suggestion.

**Comment by pablogs9** [comment]
Are you doing this part?

![image](https://user-images.githubusercontent.com/7647884/110761767-677a6080-8250-11eb-9f5b-0e79a1530883.png)

**Comment by MARLARCHAN** [comment]
Dear @pablogs9 
   I've done this. 
 cd ws_moveit2/src/moveit2/moveit_demo_nodes
 ros2 launch run_moveit_cpp run_moveit_cpp.launch.py
It run the simulation for a while and then suddenly stop it. 

The log is the following:
RuntimeError: Signal event received before subprocess transport available.
[INFO] [static_transform_publisher-1]: process started with pid [499031]
[INFO] [robot_state_publisher-2]: process started with pid [499033]
[INFO] [rviz2-3]: process started with pid [499035]
[INFO] [robot_state_publisher-2]: sending signal 'SIGINT' to process[robot_state_publisher-2]
[INFO] [static_transform_publisher-1]: sending signal 'SIGINT' to process[static_transform_publisher-1]
[ERROR] [robot_state_publisher-2]: process has died [pid 499033, exit code -2, cmd '/opt/ros/foxy/lib/robot_state_publisher/robot_state_publisher --ros-args -r __node:=robot_state_publisher --params-file /tmp/launch_params_es02030w'].
[ERROR] [static_transform_publisher-1]: process has died [pid 499031, exit code -2, cmd '/opt/ros/foxy/lib/tf2_ros/static_transform_publisher 0.0 0.0 0.0 0.0 0.0 0.0 world panda_link0 --ros-args -r __node:=static_transform_publisher'].
[rviz2-3] [INFO] [1615454018.983705369] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1615454018.983897349] [rviz2]: OpenGl version: 4.3 (GLSL 4.3)
[rviz2-3] [INFO] [1615454019.005694627] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] Parsing robot urdf xml string.
[rviz2-3] [INFO] [1615454019.103353885] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.000809676 seconds
[rviz2-3] [INFO] [1615454019.103421022] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-3] Parsing robot urdf xml string.
[rviz2-3] [INFO] [1615454019.966771185] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00170976 seconds
[rviz2-3] [INFO] [1615454019.966846920] [moveit_robot_model.robot_model]: Loading robot model 'panda'...
[rviz2-3] [WARN] [1615454019.980605861] [moveit_ros.robot_model_loader]: No kinematics plugins defined. Fill and load kinematics.yaml!
[rviz2-3] [INFO] [1615454019.995134180] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-3] [INFO] [1615454019.995657953] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/moveit_cpp/publish_planning_scene'
[rviz2-3] Warning: Invalid frame ID "panda_link0" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.9/src/buffer_core.cpp
[ERROR] [rviz2-3]: process[rviz2-3] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [rviz2-3]: sending signal 'SIGTERM' to process[rviz2-3]
[ERROR] [rviz2-3]: process has died [pid 499035, exit code -15, cmd '/opt/ros/foxy/lib/rviz2/rviz2 -d /home/marlar/ws_moveit2/install/run_moveit_cpp/share/run_moveit_cpp/launch/run_moveit_cpp.rviz --ros-args -r __node:=rviz2 --params-file /tmp/launch_params_f3iejfw0 --params-file /tmp/launch_params_7ebbq5fv'].

**Comment by pablogs9** [comment]
Please follow the instructions available in the readme

**Comment by MARLARCHAN** [comment]
Dear @pablogs9 
   I get the moveit installation.

   Now, I'm trying to run adxl372 zephyr project onto microROS. But it's not build in example app. So I add adxl372 sensor into moveit code to run on microros. In moveit, it use sensorfusion9. For adxl372 sensor, only 3axis x,y,z so that how can I use sensorfusion3. Please guide me.

**Comment by pablogs9** [comment]
Closing since not related to micro-ROS. 

This demo runs with [discovery_l475_iot1](https://os.mbed.com/platforms/ST-Discovery-L475E-IOT01A/) board and  3-axis magnetometer (LIS3MDL), 3D accelerometer and 3D gyroscope (LSM6DSL) included on it.
